### ISSUE TITLE
Would it be possible to add the vSphere packer plugins from Jetbrains?

### ISSUE THREAD

**Issue by nvpnathan** [Snapkitchen/concourse-packer-resource#7]
https://github.com/jetbrains-infra/packer-builder-vsphere
 How difficult would this be to add packer-builder-vsphere-iso & packer-builder-vsphere-clone to this resource?

**Comment by eedwards-sk** [comment]
Hey, apologies for missing your comment (I need to improve our notification settings).

This is a fairly generic (un-opinionated) packer resource, which should support any packer input vars, and any supported packer output plugins.

Can you give an example of how it's not working for your use case?

**Comment by eedwards-sk** [comment]
Hello,

Closing this issue due to lack of response.

Please feel free to re-open when you're ready.
